In [2]:
print('Hi Liyana!!!')

Hi Liyana!!!


In [2]:
import numpy
print(numpy.__version__)


2.3.5


In [17]:
import numpy as np

In [18]:
python_list =[1,2,3,"string",6,7]

numslist = [x for x in range(10)]
print(numslist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [19]:
print(numslist*3)
print(type(numslist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [21]:
arr1D = np.array([1,    2,  3])
print(arr1D)

[1 2 3]


In [34]:
arr2D = np.array([[1, 2, 3],
                  [1, 2, 3]])

print(arr2D,"\n",arr2D.ndim)           


[[1 2 3]
 [1 2 3]] 
 2


In [37]:
arr3D = np.array([[[1, 2, 3],
                   [1, 2, 3]],
                  
                  [[1, 2, 3],
                   [1, 2, 3]]])

print(arr3D,"\n",arr3D.ndim) 

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [115]:
print(f"dimension are:", arr1D.ndim)
print(f"dimension are:", arr2D.ndim)
print(f"dimension are:", arr3D.ndim)

print(f"dimension are: {np.shape(arr1D)}")
print(f"dimension are: {np.shape(arr2D)}")
print(f"dimension are: {np.shape(arr3D)}")



dimension are: 1
dimension are: 2
dimension are: 3
dimension are: (3,)
dimension are: (2, 3)
dimension are: (2, 2, 3)


In [43]:
shape1D = arr1D.ndim
shape1D

shape1D = arr1D.size
shape1D

shape1D = arr2D.size
shape1D

shape1D = arr3D.size
shape1D

12

In [49]:
type(arr1D)

numpy.ndarray

In [50]:
print(arr1D)

[1 2 3]


In [56]:
# broadcasting
arr1D * 30

arr1D + arr1D

array([2, 4, 6])

In [66]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = np.array([10,20,30,40,50])
print(arr2)

print("result: ",arr1 ** arr2)

[1 2 3 4 5]
[10 20 30 40 50]
result:  [                   1              1048576      205891132094649
                    0 -6776596920136667815]


In [65]:
a = 10
b = 3
print(a + b) # addition : 13
print(a - b) # subtraction : 7
print(a * b) # multiplication: 30
print(a / b) # division: 3.3333
print(a // b) # floor division : 3
print(a % b) # modulus : 1
print(a ** b) # exponentiation : 1000


13
7
30
3.3333333333333335
3
1
1000


In [68]:
prices = np.array([400000, 3500000, 2300000])
print(f"The price are: {prices/100000} million")

The price are: [ 4. 35. 23.] million


In [ ]:
#arange
#easiest way to create numpy array

range_of_numbers = np.arange(1,11)
range_of_numbers.reshape(5,2)
print(range_of_numbers)

#example
range_example = np.arange(1,11).reshape(5,2)
print(range_example)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [70]:
# only list comprehension we have used
nums = [x for x in range(0, 101,2)]
print(nums) 

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [110]:
nums1 = nums[100:0:-1] #accessing element in list
nums1

arraynums = np.array(nums)
print(arraynums)

print(arraynums[::-1])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2   0]


In [101]:
np.zeros((3,3))
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [135]:
np.random.seed(41)

#randomArray= np.random.rand(3,4)
#randomArray

randomArray= np.random.randint(0,100,(3,4))
randomArray

array([[64, 35, 12, 98],
       [80, 65, 89, 23],
       [85, 26, 56,  3]], dtype=int32)

In [132]:
randomArray.reshape(9,1)

array([[64],
       [35],
       [12],
       [98],
       [80],
       [65],
       [89],
       [23],
       [85]], dtype=int32)

In [138]:
flatarray = randomArray.flatten()
flatarray

reshapedarray = flatarray.reshape(6,2)
reshapedarray

array([[64, 35],
       [12, 98],
       [80, 65],
       [89, 23],
       [85, 26],
       [56,  3]], dtype=int32)

In [139]:
reshapedarray.T

array([[64, 12, 80, 89, 85, 56],
       [35, 98, 65, 23, 26,  3]], dtype=int32)

In [164]:
data = np.array([85, 94, 22, 68, 94, 54, 98])

#print(data.sum())

array_lulu = np.array([num for num in range(1,11)])
sum_of_array_lulu = array_lulu.sum()
print(sum_of_array_lulu)
print(array_lulu.mean())

55
5.5


In [169]:
a_2d_matrix = np.ones((3,5))

print(a_2d_matrix)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [170]:
a_2d_matrix.sum(axis=0)
a_2d_matrix.sum(axis=1)


array([5., 5., 5.])

In [95]:
#line = np.linspace(0, 1, 10) #values are evenly spaced and stored in array

arr = np.linspace(0, 1, 11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [144]:
number = np.array([x for x in range(1, 11)])
print(number)

total = np.sum(number)
print(total)

[ 1  2  3  4  5  6  7  8  9 10]
55


splitting numpy arrays

In [182]:
dataset_array = np.arange(1,101).reshape(50,2)
#print(dataset_array)

# x -------> y
# 1 -------> 2
# rows are 50

train_dataset = dataset_array[:25] #25 rows
test_dataset = dataset_array[25:]
print(test_dataset)

[[ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]
